all:
	make -C det
	make -C aff
	make -C aux_caus
	make -C aux_tps
	make -C de_obj

clean:
	make -C det clean
	make -C aff clean
	make -C aux_caus clean
	make -C aux_tps clean
	make -C de_obj clean
	rm -f sequoia.surf.conll
